name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Setup test environment
      run: |
        sudo mkdir /var/fixtures
        sudo chmod 777 /var/fixtures
        cp -r fixtures/fakehost/var-fixtures/* /var/fixtures 
        printf "ciao\n" > /var/fixtures/ciao.txt
        cp fixtures/fakehost/keys/fake-host /var/fixtures/private-key
        mkdir /home/runner/.ssh
        chmod 700 /home/runner/.ssh
        cp fixtures/fakehost/keys/fake-host /home/runner/.ssh/fake-host
        cp fixtures/fakehost/config /home/runner/.ssh/config 

    - name: Start fakehost container
      run: |
        docker build ./fixtures/fakehost -t meteocima/fake-ssh-host
        
    - name: Test
      run: |
        docker run \
          --name=openssh-server \
          -e PUID=1000 \
          -e PGID=1000 \
          -e TZ=Europe/London \
          -e PUBLIC_KEY='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCoFJkfmA8vG58i8RB3kwuSNoMMXjUT8TC276nHC1e4BD/nHhYAT8ddm61XI5vAJ4N+kVy94wUlhe9K3m6VOMCGWDn1zzX4wdWg297Fkq2kV5Dss/ABTj2aedoKOZisv3qkb82DNh2rfJOPv3FscNd5gRRYjboQFuQAF6qyi++u3YR/LuL8yNACEzetAxUtmVw93pOhvPj8B21ZD6iPTmUBhnvn4m3IfNcImJk4z022MoqW6EZdBJO3xuwq92Uaoe64lYjfOsSRteqZdfkrIci0G4DK/RrFqySq0FMSQnRNYjJTs2ysnyIfW4+oBKSFiniaU9KmlMszAKB/MVmiWeHcZBqEVXEeaRfp+Lm1MjfW6ly8UhloF7LTGCKXeFnrf2CI1Hghuhd1hW2fS4f9partx6luCCNincUhUtxpvChDxNkdErEWMzmYl4d2pUP3Up9w8SdIsBxPSuChTY3fLgjO/ms9IcKPSL1DY1BABo9PzfiaOq0FnZLL4PuytTGU+kftEZz5KaHxaJjxzjOzCBKXzckreNndt11jnQWWZr6sL06w0ppHAdA6093pGokpM7Z5+atnTmaND1NC+5WHlv4Oe61a2LJ2rLF2lJ5QeX8ugJ5mcWSOpSxwX4qdLteXO0N/VIrKjM0VId3EqsqWp4y7gkQ12jpCOSVAW2w/Lgo7oQ== parroit@andrea-XPS' \
          -e SUDO_ACCESS=true `#optional` \
          -e USER_NAME=andrea.parodi \
          -p 2222:2222 \
          meteocima/fake-ssh-host&
        go test -race -covermode atomic -coverprofile=covprofile ./...
        kill %1
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github